//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClockExerciser.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClockExerciser.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klokken Trainer.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actieve opdracht.
        /// </summary>
        internal static string ClockStatusLabel {
            get {
                return ResourceManager.GetString("ClockStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lees de klok en vul de tijd in (bijv. 15:30)..
        /// </summary>
        internal static string ClockToTimeInstruction {
            get {
                return ResourceManager.GetString("ClockToTimeInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bijv. 15:30.
        /// </summary>
        internal static string EntryPlaceholder {
            get {
                return ResourceManager.GetString("EntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uurwijzer.
        /// </summary>
        internal static string HourLabel {
            get {
                return ResourceManager.GetString("HourLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nederlands.
        /// </summary>
        internal static string LanguageDutch {
            get {
                return ResourceManager.GetString("LanguageDutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engels.
        /// </summary>
        internal static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taal.
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuutwijzer.
        /// </summary>
        internal static string MinuteLabel {
            get {
                return ResourceManager.GetString("MinuteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klok naar tijd.
        /// </summary>
        internal static string ModeClockToTime {
            get {
                return ResourceManager.GetString("ModeClockToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spelmodus.
        /// </summary>
        internal static string ModeLabel {
            get {
                return ResourceManager.GetString("ModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willekeurig.
        /// </summary>
        internal static string ModeRandom {
            get {
                return ResourceManager.GetString("ModeRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afwisselend lezen en zetten..
        /// </summary>
        internal static string ModeRandomDetail {
            get {
                return ResourceManager.GetString("ModeRandomDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tijd naar klok.
        /// </summary>
        internal static string ModeTimeToClock {
            get {
                return ResourceManager.GetString("ModeTimeToClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volgende opdracht.
        /// </summary>
        internal static string NextChallenge {
            get {
                return ResourceManager.GetString("NextChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gezochte tijd.
        /// </summary>
        internal static string PromptLabel {
            get {
                return ResourceManager.GetString("PromptLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goed gedaan!.
        /// </summary>
        internal static string ResultCorrect {
            get {
                return ResourceManager.GetString("ResultCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bijna, probeer opnieuw..
        /// </summary>
        internal static string ResultIncorrect {
            get {
                return ResourceManager.GetString("ResultIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondewijzer.
        /// </summary>
        internal static string SecondLabel {
            get {
                return ResourceManager.GetString("SecondLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controleer.
        /// </summary>
        internal static string SubmitAnswer {
            get {
                return ResourceManager.GetString("SubmitAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zet de wijzers gelijk aan de getoonde tijd..
        /// </summary>
        internal static string TimeToClockInstruction {
            get {
                return ResourceManager.GetString("TimeToClockInstruction", resourceCulture);
            }
        }
    }
}
